# Matching stock HybridRAW models missing from the base vendor tree.
# See camera-models.json for firmware provenance and SHA-256 checksums.
PRODUCT_COPY_FILES += \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aiFusion.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aiFusion.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aiInit.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aiInit.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_flow_front.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_flow_front.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_hdr_recovery.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_hdr_recovery.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_motion_mask_12MNormal_bs1_w8a8.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_12MNormal_bs1_w8a8.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_motion_mask_12MNormal_bs3_w8a8.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_12MNormal_bs3_w8a8.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_motion_mask_18M.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_18M.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_motion_mask_50M.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_motion_mask_50M.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_seg_human_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_human_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_seg_human_portrait.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_human_portrait.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_seg_skin.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_seg_skin.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/ai_sunset_classify.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/ai_sunset_classify.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_downNet_BackLight_Portrait_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_downNet_BackLight_Portrait_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_downNet_BackLight_Portrait_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_downNet_BackLight_Portrait_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_downNet_Sunset_Landscape_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_downNet_Sunset_Landscape_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_downNet_Sunset_Landscape_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_downNet_Sunset_Landscape_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_downNet_Sunset_Portrait_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_downNet_Sunset_Portrait_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_downNet_Sunset_Portrait_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_downNet_Sunset_Portrait_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_tonemapNet_BackLight_Portrait_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_tonemapNet_BackLight_Portrait_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_tonemapNet_BackLight_Portrait_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_tonemapNet_BackLight_Portrait_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Landscape_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Landscape_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Landscape_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Landscape_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Portrait_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Portrait_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Portrait_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_tonemapNet_Sunset_Portrait_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_upNet_BackLight_Portrait_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_upNet_BackLight_Portrait_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_upNet_BackLight_Portrait_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_upNet_BackLight_Portrait_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_upNet_Sunset_Landscape_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_upNet_Sunset_Landscape_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_upNet_Sunset_Landscape_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_upNet_Sunset_Landscape_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_upNet_Sunset_Portrait_Horizonal.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_upNet_Sunset_Portrait_Horizonal.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/aitm_upNet_Sunset_Portrait_Vertical.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/aitm_upNet_Sunset_Portrait_Vertical.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/disto_xy_2048x1536x2.raw:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/disto_xy_2048x1536x2.raw \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/front_main_binning_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/front_main_binning_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/front_main_binning_ev0_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/front_main_binning_ev0_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/front_main_binning_evm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/front_main_binning_evm.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/front_main_binning_evmm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/front_main_binning_evmm.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/gan_enhancer_20x_binning.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/gan_enhancer_20x_binning.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/gan_enhancer_40x_binning.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/gan_enhancer_40x_binning.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/gan_enhancer_80x_binning.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/gan_enhancer_80x_binning.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/gtm_curve_65536_fp32.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/gtm_curve_65536_fp32.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/jdd_enhancernet.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/jdd_enhancernet.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/jdd_enhancernet_25m.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/jdd_enhancernet_25m.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/jdd_enhancernet_night_portrait.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/jdd_enhancernet_night_portrait.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/jdd_enhancernet_pet.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/jdd_enhancernet_pet.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/main_binning_ev0_sf.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/main_binning_ev0_sf.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_ev0_3f.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_ev0_3f.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_ev0_3f_underwater.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_ev0_3f_underwater.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_ev0_motion_3f.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_ev0_motion_3f.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_ev0_night_3f.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_ev0_night_3f.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_ev0_person_3f.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_ev0_person_3f.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_evm.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_evm.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_evm_landscape.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_evm_landscape.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_evm_snapshot.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_evm_snapshot.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_binning_evmm.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_binning_evmm.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_mix_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_mix_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_mix_ev0_25M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_mix_ev0_25M.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_mix_ev0_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_mix_ev0_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_ev0_2x_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_ev0_2x_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_ev0_2x_3f_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_ev0_2x_3f_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_ev0_50m_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_ev0_50m_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_evm_2x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_evm_2x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_evm_2x_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_evm_2x_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_evm_snapshot_2x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_evm_snapshot_2x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_main_quadbayer_evmm_2x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_main_quadbayer_evmm_2x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_ev0_3x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_ev0_3x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_ev0_3x_3f.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_ev0_3x_3f.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_ev0_3x_motion_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_ev0_3x_motion_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_ev0_night_3x_3f.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_ev0_night_3x_3f.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_evm_3x.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_evm_3x.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_evm_3x_landscape.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_evm_3x_landscape.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_evm_snapshot_3x.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_evm_snapshot_3x.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_binning_evmm_3x.bix:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_binning_evmm_3x.bix \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_3f_200m.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_3f_200m.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_person.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_person.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_person_3f_200m.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_hexabayer_ev0_person_3f_200m.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_hexabayer_evm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_hexabayer_evm.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_mix_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_mix_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_mix_ev0_25M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_mix_ev0_25M.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_10x_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_10x_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_6x_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_6x_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_6x_3f_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_6x_3f_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_6x_night_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_6x_night_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_fallback.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_fallback.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_supernight.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_ev0_supernight.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_evm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_evm.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_evm_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_evm_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_evm_snapshot_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_evm_snapshot_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele1_quadbayer_evmm_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele1_quadbayer_evmm_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x_3f_person.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x_3f_person.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x_motion_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_ev0_6x_motion_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_ev0_night_6x_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_ev0_night_6x_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_evm_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_evm_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_evm_6x_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_evm_6x_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_evm_snapshot_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_evm_snapshot_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_binning_evmm_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_binning_evmm_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_mix_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_mix_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_tele2_mix_ev0_25M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_tele2_mix_ev0_25M.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_3f_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_3f_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_3f_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_3f_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_day5f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_day5f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_day_and_night_5f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_day_and_night_5f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_motion_3f_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_motion_3f_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_ev0_motion_3f_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_ev0_motion_3f_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm_higher_iso_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm_higher_iso_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm_lower_iso_landscape.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm_lower_iso_landscape.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm_snapshot_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm_snapshot_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evm_snapshot_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evm_snapshot_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evmm_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evmm_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_binning_evmm_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_binning_evmm_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_mix_ev0_25M_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_mix_ev0_25M_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/photo_uw_mix_ev0_25M_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/photo_uw_mix_ev0_25M_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/sd_noise2.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/sd_noise2.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele1_binning_ev0_sf_3x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele1_binning_ev0_sf_3x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele2_binning_ev0_sf_6x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele2_binning_ev0_sf_6x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele2_quadbayer_ev0.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele2_quadbayer_ev0.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele_binning_ev0_60x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_binning_ev0_60x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele_quadbayer_ev0_10x_18M_3f.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_quadbayer_ev0_10x_18M_3f.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele_quadbayer_ev0_20x.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_quadbayer_ev0_20x.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/tele_quadbayer_evm_10x_18M.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/tele_quadbayer_evm_10x_18M.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/uw_binning_ev0_sf_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/uw_binning_ev0_sf_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/uw_binning_ev0_sf_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/uw_binning_ev0_sf_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/uw_quadbayer_ev0_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/uw_quadbayer_ev0_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/uw_quadbayer_ev0_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/uw_quadbayer_ev0_lower_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/uw_quadbayer_evm_higher_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/uw_quadbayer_evm_higher_iso.bin \
    $(LAFA_CAMERA_PATH)/proprietary/etc/camera/hybridraw_models/uw_quadbayer_evm_lower_iso.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/hybridraw_models/uw_quadbayer_evm_lower_iso.bin
